blank_issues_enabled: false
contact_links:
  - name: 🤔 Feature Requests & Questions
    url: https://github.com/tiny-frontend/example-tiny-frontend/discussions
    about: Please ask and answer questions here.